/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mm computer
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    private HOME(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        tictactoe = new javax.swing.JButton();
        quizgame = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(36, 233, 233));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 102, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 120, 300, 100);

        tictactoe.setBackground(new java.awt.Color(102, 0, 102));
        tictactoe.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        tictactoe.setForeground(new java.awt.Color(255, 255, 255));
        tictactoe.setText("TICTACTOE");
        tictactoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tictactoeActionPerformed(evt);
            }
        });
        jPanel2.add(tictactoe);
        tictactoe.setBounds(20, 260, 300, 110);

        quizgame.setBackground(new java.awt.Color(102, 0, 102));
        quizgame.setFont(new java.awt.Font("Footlight MT Light", 0, 48)); // NOI18N
        quizgame.setForeground(new java.awt.Color(255, 255, 255));
        quizgame.setText("QUIZ GAME");
        quizgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizgameActionPerformed(evt);
            }
        });
        jPanel2.add(quizgame);
        quizgame.setBounds(20, 410, 300, 110);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(20, 20, 340, 600);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\JAVAPROJECT\\New Folder\\s1.png")); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 370, 410, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\JAVAPROJECT\\New Folder\\logo2.png")); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 10, 750, 350);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(360, 20, 850, 600);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(90, 20, 1230, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1470, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        TITLEPAGE titlepage=new TITLEPAGE();
        titlepage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tictactoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tictactoeActionPerformed
        // TODO add your handling code here:
         dispose();
        TIC_TAC_TOE tic_tac_toe=new TIC_TAC_TOE();
        tic_tac_toe.setVisible(true);
        
    }//GEN-LAST:event_tictactoeActionPerformed

    private void quizgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizgameActionPerformed
        // TODO add your handling code here:
//        
//
         question1 c=new question1();
         c.setVisible(true);
         this.dispose();
        
        
        
        
    }//GEN-LAST:event_quizgameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton quizgame;
    private javax.swing.JButton tictactoe;
    // End of variables declaration//GEN-END:variables

    
    
}
