
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mm computer
 */
public class question2 extends javax.swing.JFrame {

    private int marks;
    private int quizanswered;
  

    /**
     * Creates new form question2
     */
    public question2(int questionAnswered, int marks) {
        initComponents();
        this.quizanswered = questionAnswered;
        this.marks= marks;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnheading = new javax.swing.JLabel();
        jbtnQuestion1 = new javax.swing.JLabel();
        jbtnquesText = new javax.swing.JLabel();
        jrbtn1 = new javax.swing.JRadioButton();
        jrbtn2 = new javax.swing.JRadioButton();
        jrbtn3 = new javax.swing.JRadioButton();
        jrbtn4 = new javax.swing.JRadioButton();
        jbtnSubmitNext = new javax.swing.JButton();
        jbtnCheckAnwer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblAnswerStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jbtnheading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnheading.setForeground(new java.awt.Color(255, 255, 255));
        jbtnheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnheading.setText("Genral knowledge quiz game - 2021");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnheading, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnheading)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1420, 70);

        jbtnQuestion1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jbtnQuestion1.setText("Question 2");
        jPanel1.add(jbtnQuestion1);
        jbtnQuestion1.setBounds(20, 69, 370, 50);

        jbtnquesText.setFont(new java.awt.Font("Tahoma", 1, 31)); // NOI18N
        jbtnquesText.setText("which country is the world biggest country?");
        jPanel1.add(jbtnquesText);
        jbtnquesText.setBounds(150, 130, 750, 60);

        jrbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtn1.setText("China");
        jrbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn1);
        jrbtn1.setBounds(280, 200, 160, 60);

        jrbtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtn2.setText("India");
        jrbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn2);
        jrbtn2.setBounds(280, 280, 160, 60);

        jrbtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtn3.setText("Russia");
        jrbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn3);
        jrbtn3.setBounds(680, 190, 170, 60);

        jrbtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbtn4.setText("Canada");
        jPanel1.add(jrbtn4);
        jrbtn4.setBounds(680, 280, 170, 70);

        jbtnSubmitNext.setBackground(new java.awt.Color(0, 102, 0));
        jbtnSubmitNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnSubmitNext.setText("Submit Next");
        jbtnSubmitNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitNextActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSubmitNext);
        jbtnSubmitNext.setBounds(1090, 470, 180, 50);

        jbtnCheckAnwer.setBackground(new java.awt.Color(0, 102, 51));
        jbtnCheckAnwer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnCheckAnwer.setText("Check Answers");
        jbtnCheckAnwer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckAnwerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCheckAnwer);
        jbtnCheckAnwer.setBounds(50, 470, 190, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(null);

        lblAnswerStatus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAnswerStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswerStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswerStatus.setText("Answer Status");
        jPanel3.add(lblAnswerStatus);
        lblAnswerStatus.setBounds(301, 24, 670, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 550, 1540, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn1ActionPerformed

    private void jrbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn2ActionPerformed

    }//GEN-LAST:event_jrbtn2ActionPerformed

    private void jrbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn3ActionPerformed

    private void jbtnSubmitNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitNextActionPerformed
        // TODO add your handling code here:
        //        Question3 question3=new Question3();
        //        question3.setVisible(true);\
        if (!jrbtn1.isSelected() && !jrbtn2.isSelected() && !jrbtn3.isSelected() && !jrbtn4.isSelected()) {
            JOptionPane.showMessageDialog(null,"Please select an anwer");
        } else{
            if(jrbtn3.isSelected()){
                //assign 5 marks to marks variable
                marks = marks + 5;
                //assign questioned answered
                quizanswered = quizanswered + 1;
                //call next question window
                new question3(quizanswered, marks).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbtnSubmitNextActionPerformed

    private void jbtnCheckAnwerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckAnwerActionPerformed
        // check the user select an option. otherwise show an error message
        if (!jrbtn1.isSelected() && !jrbtn2.isSelected() && !jrbtn3.isSelected() && !jrbtn4.isSelected()) {
            JOptionPane.showMessageDialog(null,"Please select an answer");

        }else{
            //code what happen when user select an right option
            if(jrbtn3.isSelected()){
                lblAnswerStatus.setText("Correct Answer");
//                lblAnswerStatus.setForeground(color.green);
            }else{
                lblAnswerStatus.setText("inCorrect - Answer is Russia");
//                lblAnswerStatus.setForeground(color.red);

            }
            //code to lock the all radio buttons when submit check answers
            jrbtn1.setEnabled(false);
            jrbtn2.setEnabled(false);
            jrbtn3.setEnabled(false);
            jrbtn4.setEnabled(false);
        }
    }//GEN-LAST:event_jbtnCheckAnwerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question2(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnCheckAnwer;
    private javax.swing.JLabel jbtnQuestion1;
    private javax.swing.JButton jbtnSubmitNext;
    private javax.swing.JLabel jbtnheading;
    private javax.swing.JLabel jbtnquesText;
    private javax.swing.JRadioButton jrbtn1;
    private javax.swing.JRadioButton jrbtn2;
    private javax.swing.JRadioButton jrbtn3;
    private javax.swing.JRadioButton jrbtn4;
    private javax.swing.JLabel lblAnswerStatus;
    // End of variables declaration//GEN-END:variables
}
