
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mm computer
 */
public class question6 extends javax.swing.JFrame {

    private int marks;
    private int quizanswered;
    /**
     * Creates new form question6
     */
    public question6(int questionAnswered, int marks) {
        initComponents();
        this.quizanswered = questionAnswered;
        this.marks= marks;

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnheading = new javax.swing.JLabel();
        jbtnQuestion1 = new javax.swing.JLabel();
        jbtnquesText = new javax.swing.JLabel();
        jrbtn1 = new javax.swing.JRadioButton();
        jrbtn2 = new javax.swing.JRadioButton();
        jrbtn3 = new javax.swing.JRadioButton();
        jrbtn4 = new javax.swing.JRadioButton();
        jbtnSubmitNext = new javax.swing.JButton();
        jbtnCheckAnwer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblAnswerStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(null);

        jbtnheading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnheading.setForeground(new java.awt.Color(255, 255, 255));
        jbtnheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnheading.setText("Genral knowledge quiz game - 2021");
        jPanel2.add(jbtnheading);
        jbtnheading.setBounds(220, 20, 890, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1400, 70);

        jbtnQuestion1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnQuestion1.setText("Question 6");
        jPanel1.add(jbtnQuestion1);
        jbtnQuestion1.setBounds(40, 80, 140, 40);

        jbtnquesText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnquesText.setText("Urdu is a?");
        jPanel1.add(jbtnquesText);
        jbtnquesText.setBounds(190, 120, 398, 40);

        jrbtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtn1.setText("Persian word");
        jrbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn1);
        jrbtn1.setBounds(160, 180, 180, 40);

        jrbtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtn2.setText("Indian word");
        jrbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn2);
        jrbtn2.setBounds(160, 240, 180, 50);

        jrbtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtn3.setText("Arabic word");
        jrbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn3);
        jrbtn3.setBounds(500, 180, 220, 40);

        jrbtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtn4.setText("Turkish word");
        jPanel1.add(jrbtn4);
        jrbtn4.setBounds(500, 230, 220, 40);

        jbtnSubmitNext.setBackground(new java.awt.Color(0, 102, 0));
        jbtnSubmitNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnSubmitNext.setText("Submit Next");
        jbtnSubmitNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitNextActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSubmitNext);
        jbtnSubmitNext.setBounds(750, 333, 240, 50);

        jbtnCheckAnwer.setBackground(new java.awt.Color(0, 102, 51));
        jbtnCheckAnwer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnCheckAnwer.setText("Check Answers");
        jbtnCheckAnwer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckAnwerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCheckAnwer);
        jbtnCheckAnwer.setBounds(40, 340, 260, 50);

        jPanel4.setBackground(new java.awt.Color(204, 204, 0));
        jPanel4.setLayout(null);

        lblAnswerStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAnswerStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswerStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswerStatus.setText("Answer Status");
        jPanel4.add(lblAnswerStatus);
        lblAnswerStatus.setBounds(178, 25, 240, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 410, 1400, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1400, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn1ActionPerformed

    private void jrbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn2ActionPerformed

    private void jrbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn3ActionPerformed

    private void jbtnSubmitNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitNextActionPerformed
        // TODO add your handling code here:
        if (!jrbtn1.isSelected() && !jrbtn2.isSelected() && !jrbtn3.isSelected() && !jrbtn4.isSelected()) {
            JOptionPane.showMessageDialog(null,"Please select an anwer");
        } else{
            //check correct answer
            if(jrbtn4.isSelected()){
                //assign 5 marks to marks variable
                marks = marks + 5;
            }
            //assign questioned answered
            quizanswered = quizanswered + 1;
            //call next question window
            new question7(quizanswered, marks).setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jbtnSubmitNextActionPerformed

    private void jbtnCheckAnwerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckAnwerActionPerformed
        // check the user select an option. otherwise show an error message
        if (!jrbtn1.isSelected() && !jrbtn2.isSelected() && !jrbtn3.isSelected() && !jrbtn4.isSelected()) {
            JOptionPane.showMessageDialog(null,"Please select an anwer");

        }else{
            //code what happen when user select an right option
            if(jrbtn4.isSelected()){
                lblAnswerStatus.setText("Correct Answer");
//                lblAnswerStatus.setForeground(color.green);
            }else{
                lblAnswerStatus.setText("inCorrect - Answer is a Turkish Word");
//                lblAnswerStatus.setForeground(color.red);

            }
            //code to lock the all radio buttons when submit check answers
            jrbtn1.setEnabled(false);
            jrbtn2.setEnabled(false);
            jrbtn3.setEnabled(false);
            jrbtn4.setEnabled(false);
        }
    }//GEN-LAST:event_jbtnCheckAnwerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question6(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnCheckAnwer;
    private javax.swing.JLabel jbtnQuestion1;
    private javax.swing.JButton jbtnSubmitNext;
    private javax.swing.JLabel jbtnheading;
    private javax.swing.JLabel jbtnquesText;
    private javax.swing.JRadioButton jrbtn1;
    private javax.swing.JRadioButton jrbtn2;
    private javax.swing.JRadioButton jrbtn3;
    private javax.swing.JRadioButton jrbtn4;
    private javax.swing.JLabel lblAnswerStatus;
    // End of variables declaration//GEN-END:variables
}
